project:
  type: website
  output-dir: docs

website:
  title: "DATASCI 350 - Quiz 02"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: life-gdp.qmd
        text: Life & GDP
      - href: life-population.qmd
        text: Life & Population
      - href: country.qmd
        text: Country Analysis

format:
  html:
    theme: minty
